source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'mysql2', '~> 0.3.13'

#Assets
gem 'bootstrap-sass', '~> 3.3'
gem 'autoprefixer-rails', '~> 5.1'
gem 'sass-rails', '~> 5.0'
gem 'therubyracer','0.12.1', :platforms => :ruby
gem 'uglifier', '~> 2.7'
gem 'jquery-rails', '~> 4.0'
gem 'jquery-ui-sass-rails', '~> 4.0'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

#Authentication & Authorizations
gem 'authlogic', '~> 3.4'
gem 'omniauth', '~> 1.2'
gem 'omniauth-google-oauth2', '~> 0.2'
gem 'cancancan', '~> 1.10'

#ActiveRecord stuffs and Background Job
gem 'validates_email_format_of', '~> 1.6.2'
gem 'protected_attributes', '~> 1.0.8'
gem 'delayed_job_active_record', '~> 4.0.3'
gem 'delayed_job', '~> 4.0.6'
gem 'activerecord-session_store', '~> 0.1'

#Rails 4 stuffs backward-support for code written in Rails 2 or 3
gem 'activerecord-deprecated_finders', '~> 1.0'

#HTML & Parsers
gem 'nokogiri', '~> 1.6'
gem 'hpricot', '~> 0.8'
gem 'text', '~> 1.3'
gem 'will_paginate', '~> 3.0'
gem 'mechanize', '~> 2.7'

#Net SSH,SCP,SFTP
gem 'net-sftp', '~> 2.1', :require => 'net/sftp'
gem 'net-ssh', '~> 2.9', :require => 'net/ssh'
gem 'net-scp', '~> 1.2', :require => 'net/scp'

#Money
gem 'money', '~> 6.5'
gem 'monetize', '~> 1.3'

#Caching with Memcache
gem 'dalli', '~> 2.7'

#Crons
gem 'whenever','~> 0.9', :require => true

#Search
gem 'rsolr','~> 1.0'
gem 'rsolr-ext','~> 1.0'

#State Machine
gem 'state_machine', '~> 1.2'

#Others
gem 'hirb', '0.7.3'
gem 'interactive_editor', '0.0.10'
gem 'fastercsv', '~> 1.5',:require => true
gem 'daemons', '~> 1.1'
gem 'passenger','~> 4.0.59'
gem 'zip-zip', '~> 0.3'
gem 'rubyzip', '~> 1.1.7', :require => 'zip/zip'
gem 'oj', '~> 2.10', :require => 'oj'

